bundle_manager:
    adapter:
        name: 'local_filesystem'    # the name of the adapter which get returned by AdapterInterface::getName()
        options: null               # to pass custom key-value pairs to the adapter implementation
