document_manager:
    connections:
        filesystemConnection:
            driver: 'filesystem'
            options: []
    handlers:
        filesystemHandler:
            connection: filesystemConnection
            classes: null
